default_install_hook_types:
  - pre-commit
  - post-commit
  - commit-msg

repos:
  - repo: local
    hooks:
      - id: clippy fix
        name: fix easy clippy stuff
        entry: cargo clippy --fix --allow-dirty
        language: rust
        pass_filenames: false
        fail_fast: true
      - id: clippy check
        name: check for bad things in rust code
        entry: cargo clippy --workspace
        language: rust
        pass_filenames: false
        always_run: true
        fail_fast: true
  # common checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: forbid-submodules
  # code spellcheck
  - repo: https://github.com/crate-ci/typos
    rev: v1.50.2
    hooks:
      - id: typos
  # lints git commit messages
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1 # Fill in a tag / sha here (e.g. v0.19.1)
    hooks:
      - id: gitlint
        args: [--ignore, body-is-missing, --staged, --msg-filename]
  - repo: local
    hooks:
      - id: git-cliff-changelog
        name: git-cliff-changelog
        entry: >-
          bash -c '
            LAST_TAG=$(bash -c "git tag --sort=committerdate|tail -n 1")
            TAG=v$(cargo metadata --format-version 1| jq -r '.packages[0].version')
            if [[ "$LAST_TAG" == "$TAG" ]]; then
                TAG=""
            fi
            echo $TAG
            git-cliff -t "$TAG" -o CHANGELOG.md &&
            if ! git diff --quiet -- CHANGELOG.md; then
                git add CHANGELOG.md &&
                git commit --amend --no-edit --no-verify
            fi
          '
        language: system
        pass_filenames: false
        always_run: true
        stages: [post-commit]
