name: Rust CI
on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "master"
      - "devel"

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Setup Environment
        run: |
          echo "PKG_NAME=rs-base" >> "$GITHUB_ENV"
      - uses: actions/cache/restore@v5
        with:
          path: |
            target
            /root/.rustup
            /root/.cargo
          key: ${{ env.PKG_NAME }}-${{ runner.os }}
      - name: Install Rust toolchain
        uses: https://git.cscherr.de/actions/rust-toolchain@stable
      - name: Run tests
        run: cargo test --all-features --workspace
      - uses: actions/cache/save@v5
        with:
          path: |
            target
            /root/.rustup
            /root/.cargo
          key: ${{ env.PKG_NAME }}-${{ runner.os }}

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Setup Environment
        run: |
          echo "PKG_NAME=rs-base" >> "$GITHUB_ENV"
      - uses: actions/cache/restore@v5
        with:
          path: |
            target
            /root/.rustup
            /root/.cargo
          key: ${{ env.PKG_NAME }}-${{ runner.os }}
      - name: Install Rust toolchain
        uses: https://git.cscherr.de/actions/rust-toolchain@stable
        with:
          components: clippy,rustfmt
      - name: Clippy check and fix
        run: cargo clippy --fix --all-features --workspace
      - name: Check formatting
        run: cargo fmt --all
      - name: commit back to repository
        uses: https://git.cscherr.de/actions/git-auto-commit-action@v7
        with:
          commit_user_name: forgejo-actions
          commit_user_email: forgejo-actions@cscherr.de
          commit_author: "forgejo-actions <forgejo-actions@cscherr.de>"
          commit_message: "chore(ci): automatic Rust CI changes"

  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Setup Environment
        run: |
          echo "PKG_NAME=rs-base" >> "$GITHUB_ENV"
      - uses: actions/cache/restore@v5
        with:
          path: |
            target
            /root/.rustup
            /root/.cargo
          key: ${{ env.PKG_NAME }}-${{ runner.os }}
      - name: Install Rust toolchain
        uses: https://git.cscherr.de/actions/rust-toolchain@stable
      - name: Check documentation
        env:
          RUSTDOCFLAGS: -D warnings
        run: cargo doc --no-deps --document-private-items --all-features --workspace --examples

  msrv:
    name: Check compatible rust version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Setup Environment
        run: |
          echo "PKG_NAME=rs-base" >> "$GITHUB_ENV"
      - uses: actions/cache/restore@v5
        with:
          path: |
            target
            /root/.rustup
            /root/.cargo
          key: ${{ env.PKG_NAME }}-${{ runner.os }}
      - name: Install Rust toolchain
        uses: https://git.cscherr.de/actions/rust-toolchain@stable
      - uses: https://git.cscherr.de/actions/cargo-binstall@main
      - name: install cargo-msrv
        run: cargo binstall cargo-msrv --force
      - name: Verify rust version
        run: cargo msrv verify
