name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Setup Environment
        run: |
          echo "PKG_NAME=$(grep -Po '(?<=^name = ")[^"]*(?=".*)' Cargo.toml)" >> "$GITHUB_ENV"
          echo "PKG_VERSION=$(grep -Po '(?<=^version = ")[^"]*(?=".*)' Cargo.toml)" >> "$GITHUB_ENV"
      - uses: actions/cache/restore@v5
        id: cache-release
        with:
          path: |
            target
            /root/.rustup
            /root/.cargo
          key: ${{ env.PKG_NAME }}-${{ runner.os }}-release
      - name: Install Rust toolchain
        uses: https://git.cscherr.de/actions/rust-toolchain@stable
      - uses: https://git.cscherr.de/actions/cargo-binstall@main
      - name: Run tests
        run: cargo test --all-features --workspace
      - name: Cargo publish
        uses: https://git.cscherr.de/actions/action-cargo-publish@v0.1.0
        with:
          path: "."
          token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          dry-run: false
      - uses: actions/cache/save@v5
        id: cache-release
        with:
          path: |
            target
            /root/.rustup
            /root/.cargo
          key: ${{ env.PKG_NAME }}-${{ runner.os }}-release
      - name: just tag
        run: git tag v${{ steps.metadata.outputs.package_version }} HEAD
      - name: just push tags
        run: git push --tags
