name: Release-plz

permissions:
  pull-requests: write
  contents: write

on:
  push:
    branches:
      - master

jobs:

  # Release unpublished packages.
  release-plz-release:
    name: Release-plz release
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: https://github.com/dtolnay/rust-toolchain@stable
      - name: Manually Install binaries
        uses: https://github.com/taiki-e/install-action@v2
        with:
          tool: cargo-semver-checks@0.35, release-plz@0.3.102 # hack
      - name: Run release-plz
        uses: https://github.com/MarcoIeni/release-plz-action@v0.5
        with:
          backend: gitea
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
